project_gallery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from gallery import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.gallery_view, name='main'),
    path('image/<int:pk>/', views.image_detail, name='image_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Image(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='gallery_images/')
    categories = models.ManyToManyField(Category, blank=True)
    created_date = models.DateField()
    age_limit = models.PositiveIntegerField()

    def __str__(self):
        return self.title

gallery/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Image


def gallery_view(request):
    categories = Category.objects.all()
    return render(request, "gallery.html", {"categories": categories})


def image_detail(request, pk):
    image = get_object_or_404(Image, pk=pk)
    return render(request, "image_detail.html", {"image": image})

gallery/templates/gallery.html
{% extends 'base.html' %}

{% block content %}
    <h1>All Images by Category</h1>
    <div class="row">
        {% for category in categories %}
            <div class="col-md-12">
                <h2>{{ category.name }}</h2>
                <div class="row">
                    {% for image in category.image_set.all %}
                        <div class="col-md-4">
                            <div class="card mb-4">
                                <img src="{{ image.image.url }}" class="card-img-top" alt="{{ image.title }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ image.title }}</h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

gallery/templates/image_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <img src="{{ image.image.url }}" class="card-img-top" alt="{{ image.title }}">
        <div class="card-body">
            <h5 class="card-title">{{ image.title }}</h5>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>